### ISSUE TITLE
Please make this a gem

### ISSUE THREAD

**Issue by petethepig** [thisredone/rb#1]
I understand this is a very short script, but it is just much easier to type `gem install something` than copy pasting code.

**Comment by tonekk** [comment]
No need for copy pasting:

```
 curl -sL http://bit.ly/install-rb-util | bash -
```

Might be worth putting into the README, will create a PR.

EDIT: https://github.com/thisredone/rb/pull/5

**Comment by thisredone** [comment]
I think the current one-liner provided by @Ajedi32 in #8 is sufficient
