### ISSUE TITLE
add K/M/G unit conversions out of the box

### ISSUE THREAD

**Issue by rosenfeld** [thisredone/rb#12]
I understand that rb is supposed to be a showcase for how ruby can handle common tasks with just a few lines, but this script could be actually even more useful if it provided some common conversions that would be desired for common scripts and that are not provided by Ruby core out of the box.

For example, it's quite common to see some output displayed using units such as 131K, 14M or 300G. If the script could provide some sample methods for handling such conversions it would allow rb to be called such as:

```shell
du -chs * | rb 'sort_by{|l| - to_bytes(l.split.first) }'
```

Of course, for this particular case it's simpler to call `du -chs * | sort -n -r`, but there are some scenarios where setting the logic with ruby would be easier.

Such helper could be implemented such as

```ruby
def to_bytes(n)
  zeros = { 'k' => 3, 'm' => 6, 'g' => 9 }
  n.sub(/([kmg])/i){|m| '0' * zeros[m.downcase] }.to_f
end
```

**Comment by rosenfeld** [comment]
In that sense, the more popular such approach becomes, the better is the argument for turning this into a gem as it becomes more specialized or accept more options... The Unix philosophy is to provide small tools that do just one thing and do it well, but not all tools would have to follow such advice. Sometimes coordinating all those tools to work together requires quite some effort and a generic tool that does everything may well work better under those scenarios :) Maybe rb could become such an alternative, providing many switches to make it easier to perform common tasks and providing some useful methods out of the box when it makes sense.

**Comment by thisredone** [comment]
This goes slightly against the sexyness of the project - being small and instantly understood. _But_ it's entirely possible for `rb` to require a `rb-utils` (or whatever) gem if it's available in the system and thus keeping everyone happy.
I guess it depends on whether or not we can come up with enough useful things to make it worthwhile. Considering the nature of this project we could perhaps even get away with monkey patching here.
I'm open to ideas.

**Comment by rosenfeld** [comment]
Yes, I totally understand that. Regarding requiring an external gem, I think that only makes sense if you bundle rb as a gem or otherwise the script couldn't just assume the gem will be there. It could detect and print some instructions on how to fix it, but it seems to me that bundling rb as a gem would avoid all those issues...

I wouldn't bother with monkey patches for this particular case. It's a very specific use case and methods to aid with the common tasks are welcome I think. I just think that if that project was targetting to be really really useful as a generic text manipulation tool it has great potential as being based on Ruby's syntax for that, but since scripts should be usually one-liners it would be greatly enhanced if it provided some common helpers out of the box so that it could be used to support several common text manipulation operations. That means that it might have to support some additional flags in the future as well to better support some common cases (I haven't thought a lot about such usages yet, but it seems reasonable that it would get more flags as it gets more used). So, if this is going to be a really really powerful text manipulation tool it would have to evolve from the sexy 10-lines script to something more ellaborate :)

**Comment by andyl** [comment]
It grows!

```ruby
# add bytes and neg_bytes methods
class String
  def bytes
    return 0 if self.empty?
    zeros = { 'k' => 3, 'm' => 6, 'g' => 9 }
    self.sub(/([kmg])/i) {|m| '0' * zeros[m.downcase]}.sub(/\..*/) {|m| m[1..-2]}.to_i
  end

  def neg_bytes
    -1 * self.bytes
  end
end

# add hsort - sort by human-readable sizes
class Array
  def hsort
    sort_by {|line| String(line[/(\d+(\.\d)?[KGM]|\d\d+)/, 1]).neg_bytes}
  end
end
```
To use:
```ruby
$ du -hs * | rb hsort
$ ls -lh | rb hsort
$ ls -l | rb hsort
```

**Comment by thisredone** [comment]
@rosenfeld script can `require` a gem but `rescue LoadError`

**Comment by rosenfeld** [comment]
It can but it has to print a warning in case someone would be expecting the helpers to be available. Bundling as a gem would avoid having to think or work around such issues.

**Comment by thisredone** [comment]
Well, the warning couldn't be printed since then it'd be too annoying to use `rb` without the helpers.
I think additional utilities should be opt-in. Perhaps a note about them in the `README.md` would be sufficient. The code could like something like this:

```ruby
#!/usr/bin/env ruby
begin
  require 'rb-cli-utils`
rescue LoadError
end

def execute(_, code)
# (...)
```

**Comment by rosenfeld** [comment]
@andyl indeed my previous suggestion would only work with integer values followed by k, m or g. To support decimal places and common locales (accepting both ',' and '.') and assuming no thousands separators are used, something like this might work for most cases with better precision (assuming 1k = 1024 bytes, for example):

```ruby
class String
  BYTES_POWERS = { 'k' => 1, 'm' => 2, 'g' => 3 }.freeze
  def to_bytes # the bytes method already exist for String
    n = sub(',', '.').to_f
    power = BYTES_POWERS[strip[-1]&.downcase] and n*1024**power or n
  end
end
```

Of course it's not thread-safe but it's supposed to be used as a command-line tool :)

The addition to array for hsort, and possibly revhsort could be quite useful indeed. I believe hsort should sort by smaller numbers first, though, just like the sort command :)

**Comment by rosenfeld** [comment]
@thisredone 

My problem with that approach is that from a sysadmin point of view, this is not desirable as the same command could yield to different results whether or not the library is available in a particular system...

In that sense, I belive it would make more sense to make those separate commands such as rb and erb (standing for extended rb, but it could be mistaken by the erubis extension). The erb command would then require rb-utils but in that case I really think erb should become a gem to make sure rb-utils exist if `which erb` is successful. I do often work as sysadmin when working on our deployment scripts, for example, so I think it would make it much easier to simplify the procedures by ensuring erb exists with something like "which erb > /dev/null || gem install --no-ri --no-rdoc -q erb". Weirdly enough it seems the erb gem doesn't exist yet :)

**Comment by andyl** [comment]
@rosenfeld - nice!

```ruby
# add hbytes and hmatch methods class String
class String

  HPOWERS = { 'K' => 3, 'M' => 6, 'G' => 9 }.freeze

  def hbytes
    return 0 if self.empty?
    sub(/([KMG])/) {|m| '0' * HPOWERS[m]}.sub(/\..*/) {|m| m[1..-2]}.to_i
  end

  def hmatch
    gsub(',', '.').upcase[/(\d+(\.\d)?[KMG]|\d\d+)/, 1] || ''
  end
end

# add hsort - sort by human-readable sizes
class Array
  def hsort
    sort_by {|line| line.hmatch.hbytes}
  end
end

```

To use:
```ruby
$ du -hs * | rb hsort
$ du -hs * | rb hsort.reverse
$ du -hs * | rb -l hmatch
$ du -hs * | rb -l hmatch.hbytes
$ ls -lh | rb hsort
$ ls -l  | rb hsort
$ ls -lh | rb -l hmatch
```

**Comment by rosenfeld** [comment]
@andyl Your hbytes implementation doesn't seem to work (I slightly modified it to support lower case suffixes):

```ruby
['123.456m', '123.456k'].each{|s| puts s.sub(/([KMG])/i) {|m| '0' * HPOWERS[m.upcase]}.sub(/\..*/) {|m| m[1..-2]}.to_i }
# 12345600000
# 12345600
# it's missing one zero in both cases
```

The method I described in https://github.com/thisredone/rb/issues/12#issuecomment-413842558 seems safer I think.

**Comment by andyl** [comment]
@rosenfeld - yeah - well there's enough here for an interested onlooker to use and tweak if they wish.  Thanks for posting your `to_bytes` idea and kudos to @thisredone for `rb` it's very nice.

**Comment by pvdb** [comment]
I'm leaning towards keeping `rb` lean and sexy, and not bloat it with anything, no matter how useful it'd be _(in certain circumstances, but not others)_.

As much as unit conversion is indeed a very useful thing to have _(heck, I think everyone must have their own collection of utilities or libraries in their specific language or environment)_ the next person will think color-printing strings in the console is a must-have, and the person after that cannot live without creating gists from the command line.

If you need to pull in a library or gem to make some extensions available to `rb` then you can always use the following idiom:

```
$ ( echo 15; echo 32; ) | ruby -r prime $(which rb) -l to_i.prime_division.inspect
[[3, 1], [5, 1]]
[[2, 5]]
$ _
```

... which - I agree - isn't as elegant as invoking `rb` directly, but on the other hand, you can require as many Ruby `stdlib` libraries and as many Ruby gems as you want and need!

This approach is much more general purpose IMO: the user of `rb` decides which extension(s) to require for the task at hand _(and only then)_, instead of being limited to whatever extensions have been accepted into `rb` by its [BDFL](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life) :smiley:

And if you find yourself pulling in the same extensions over and over again, it'd be easy enough to devise a shell alias or a wrapper script that proxies the original `rb`.

**Comment by nogweii** [comment]
Would it make sense to expand `rb` to support passing `-r`? Thus, @pvdb's prior example would turn into:

    $ ( echo 15; echo 32; ) | rb -rprime -l to_i.prime_division.inspect

Which I think still keeps it inline with the original intent.

**Comment by nashbridges** [comment]
Looks like evaling $HOME/.rbrc (if exists) would solve all customization issues, including monkey patching core classes.

**Comment by thisredone** [comment]
Anyone want's to do a PR? (I'm on vacation)

**Comment by thisredone** [comment]
#16
