### ISSUE TITLE
good idea

### ISSUE THREAD

**Issue by xiejiangzhi** [thisredone/rb#3]
maybe one line enough, haha

```
#! /usr/bin/env ruby

puts $stdin.readlines.map(&:strip).instance_eval(ARGV.join(' '))
```

**Comment by DarkWiiPlayer** [comment]
puts $stdin.each_line.tap(&:strip!)instance_eval(ARGV.join(' ')) # <3

This way it doesn't first read the entire file but executes line by line to 1) save memory and 2) not let others wait down the pipeline. Comment for decorative purposes only.

**Comment by thisredone** [comment]
Well it is :). But the `-l` is also useful here and there
